// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ReiDosPiratas.Infrastructure.Data;

#nullable disable

namespace ReiDosPiratas.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReiDosPiratas.Domain.Entities.Produto", b =>
                {
                    b.Property<long>("Produto_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Produto_ID"));

                    b.Property<float>("Altura")
                        .HasColumnType("BINARY_FLOAT")
                        .HasColumnName("ALTURA");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("AUTOR");

                    b.Property<int>("Categoria")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CATEGORIA");

                    b.Property<int>("Condicao_produto")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CONDICAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int>("Estoque")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ESTOQUE");

                    b.Property<long>("FuncionarioId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("FUNCIONARIO_ID");

                    b.Property<string>("Imagem_url")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ENDERECO_IMAGEM");

                    b.Property<float>("Largura")
                        .HasColumnType("BINARY_FLOAT")
                        .HasColumnName("LARGURA");

                    b.Property<double?>("Peso")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("PESO");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRECO");

                    b.Property<decimal>("Preco_original")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRECO_ORIGINAL");

                    b.Property<float>("Profundidade")
                        .HasColumnType("BINARY_FLOAT")
                        .HasColumnName("PROFUNDIDADE");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("NOME");

                    b.HasKey("Produto_ID");

                    b.ToTable("PRODUTOS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
